module.exports = {
  sass_compile_imports: {
      compile: {
          target: '../src/Styles/main.scss',
          files: [{
              expand: true,
              cwd: '../src/Styles/Sass',
              src: ['../**/*.scss']
          }]
      },
      options: {
          header: [
              '//Do not edit this file - if you need to add new files run the sass_compile_imports script. There is no grunt task for compiling sass as Aaron does this in terminal seperate for a better workflow, Happy developing!'
          ]
      }
  }
};
