module.exports = function(grunt) {


    grunt.initConfig({

        sass_compile_imports: {
            compile: {
                target: 'Styles/main.scss',
                files: [{
                    expand: true,
                    cwd: 'Styles/Sass',
                    src: ['**/*.scss']
                }]
            },
            options: {
                header: [
                    '//Do not edit this file - if you need to add new files run the sass_compile_imports script. There is no grunt task for compiling sass as Aaron does this in terminal seperate for a better workflow, Happy developing!'
                ]
            }
        },

        browserSync: {
            dev: {
                bsFiles: {
                    src: [
                        'Styles/Sass/*.css',
                        '*.html'
                    ]
                },
                options: {
                    watchTask: true,
                    server: './blank',
                    proxy: "blank-project.dev"
                }
            }
        },
        imagemin: {                          // Task
    static: {                          // Target
      options: {                       // Target options
        optimizationLevel: 3,
        svgoPlugins: [{ removeViewBox: false }]
      }
    },
    dynamic: {                         // Another target
      files: [{
        expand: true,                  // Enable dynamic expansion
        cwd: 'Images/',                   // Src matches are relative to this path
        src: ['**/*.{png,jpg,gif}'],   // Actual patterns to match
        dest: 'Images/'                  // Destination path prefix
      }]
    }
  },
  html_validator: {
      validation: {
          options: {
              directories: ['../Blank-Project/index.html']
          }
      }
  },
        watch: {
            scripts: {
                files: ['**/*'],
                tasks: [''],
                options: {
                    spawn: false,
                },
            },
        },


    });
    grunt.loadNpmTasks('grunt-sass-compile-imports');
    grunt.loadNpmTasks('grunt-browser-sync');
    grunt.loadNpmTasks('grunt-contrib-imagemin');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-html-validator');





    grunt.registerTask('default', ['sass_compile_imports']);

};
